/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BotConfigDialog: typeof import('./src/components/BotConfigDialog.vue')['default']
    ChatArea: typeof import('./src/components/chat/ChatArea.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatSidebar: typeof import('./src/components/chat/ChatSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
  }
}
